import {
  asymptoticArenaMission,
  bayesForkMission,
  bernoulliLabMission,
  bstQuestMission,
  determinantForgeMission,
  dpStationMission,
  dsuForestMission,
  eigenChaseMission,
  expectationLabMission,
  eulerTrailMission,
  fourierSynthMission,
  gaussStationMission,
  gradientSlopeMission,
  heapForgeMission,
  taylorLabMission,
  pascalTriangleMission,
  monteCarloMission,
  rootsOrbitMission,
  featureFactoryMission,
  graphDispatcherMission,
  kernelHuntMission,
  matrixMachineMission,
  mlPlaygroundMission,
  orthogonalWorkshopMission,
  pcaCompressionMission,
  quadraticLensMission,
  svdLensMission,
  substitutionWorkshopMission,
  unitaryCompassMission,
} from '../game/missions'
import type { VizEntry } from './registryTypes'
import {
  AsymptoticArenaMission,
  BernoulliLabMission,
  BstQuestMission,
  DeterminantForgeMission,
  DpStationMission,
  DsuForestMission,
  EigenChaseMission,
  EulerTrailMission,
  FourierSynthMission,
  GaussStationMission,
  GradientSlopeMission,
  HeapForgeMission,
  MonteCarloMission,
  BayesForkMission,
  ExpectationLabMission,
  TaylorLabMission,
  PascalTriangleMission,
  RootsOrbitMission,
  FeatureFactoryMission,
  GraphDispatcherMission,
  KernelHuntMission,
  MatrixMachineMission,
  MlPlaygroundMission,
  OrthogonalWorkshopMission,
  PcaCompressionMission,
  QuadraticLensMission,
  SvdLensMission,
  SubstitutionWorkshopMission,
  UnitaryCompassMission,
} from './routeLoaders'

export const missionEntries: VizEntry[] = [
  {
    id: 'kernel',
    path: '/algebra/linear-maps/kernel',
    title: 'Охота за ядром',
    kind: 'mission',
    status: 'available',
    difficulty: 1,
    lessonPath: kernelHuntMission.lessonPath,
    mission: kernelHuntMission,
    component: KernelHuntMission,
    meta: {
      title: 'Охота за ядром',
      sceneTitle: 'Геометрия ядра линейного отображения',
      formula: String.raw`\ker\varphi=\mathrm{span}\{(-1,1,-1)\}`,
      description: 'Ядро всегда является подпространством: здесь это прямая через начало.',
      note:
        'Плоскость на схеме — вспомогательный фрагмент, напоминающий о структуре уравнений Ax=0 (само ядро в примере — прямая, а не эта плоскость).',
    },
  },
  {
    id: 'forge',
    path: '/algebra/determinants/forge',
    title: 'Кузница определителя',
    kind: 'mission',
    status: 'available',
    difficulty: 1,
    lessonPath: determinantForgeMission.lessonPath,
    mission: determinantForgeMission,
    component: DeterminantForgeMission,
    meta: {
      title: 'Кузница определителя',
      formula: String.raw`\det\begin{pmatrix}a&b\\c&d\end{pmatrix}=ad-bc`,
      description:
        'Два столбца матрицы задают параллелограмм: площадь, ориентация и обратимость видны через определитель.',
    },
  },
  {
    id: 'matrix-machine',
    path: '/algebra/matrices/machine',
    title: 'Матрица как машина',
    kind: 'mission',
    status: 'available',
    difficulty: 1,
    lessonPath: matrixMachineMission.lessonPath,
    mission: matrixMachineMission,
    component: MatrixMachineMission,
    meta: {
      title: 'Матрица как машина',
      formula: String.raw`A=[Ae_1\ Ae_2]`,
      description:
        'Матрица задается образами базисных векторов: эти образы становятся ее столбцами.',
    },
  },
  {
    id: 'quadratic-lens',
    path: '/algebra/quadratic-forms/lens',
    title: 'Квадратичная линза',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: quadraticLensMission.lessonPath,
    mission: quadraticLensMission,
    component: QuadraticLensMission,
    meta: {
      title: 'Квадратичная линза',
      formula: String.raw`q(x,y)=ax^2+2bxy+cy^2`,
      description:
        'Квадратичная форма превращается в эллипс, седло или вырожденное направление; главные оси убирают смешанный член.',
    },
  },
  {
    id: 'svd-lens',
    path: '/algebra/svd/lens',
    title: 'SVD-линза',
    kind: 'mission',
    status: 'available',
    difficulty: 3,
    lessonPath: svdLensMission.lessonPath,
    mission: svdLensMission,
    component: SvdLensMission,
    meta: {
      title: 'SVD-линза',
      formula: String.raw`A=U\Sigma V^T`,
      description:
        'Единичный круг проходит через матрицу и становится эллипсом: его полуоси показывают сингулярные числа, а PCA появляется как rank-1 тень данных.',
    },
  },
  {
    id: 'pca-compression-lab',
    path: '/algebra/svd/pca-compression',
    title: 'PCA-компрессор',
    kind: 'mission',
    status: 'available',
    difficulty: 3,
    lessonPath: pcaCompressionMission.lessonPath,
    mission: pcaCompressionMission,
    component: PcaCompressionMission,
    meta: {
      title: 'PCA-компрессор',
      formula: String.raw`A_k=\sum_{i=1}^k \sigma_i u_i v_i^T`,
      description:
        'Сингулярные компоненты превращаются в практическое сжатие: storage budget, reconstruction error и residual artifacts.',
    },
  },
  {
    id: 'orthogonal-workshop',
    path: '/algebra/euclidean/orthogonal-workshop',
    title: 'Евклидова мастерская',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: orthogonalWorkshopMission.lessonPath,
    mission: orthogonalWorkshopMission,
    component: OrthogonalWorkshopMission,
    meta: {
      title: 'Евклидова мастерская',
      formula: String.raw`x=\mathrm{proj}_U x+r,\quad r\perp U`,
      description:
        'Проекция, остаток и Грам-Шмидт становятся игровыми операциями над ортогональностью.',
    },
  },
  {
    id: 'unitary-compass',
    path: '/algebra/complex/unitary-compass',
    title: 'Унитарный компас',
    kind: 'mission',
    status: 'available',
    difficulty: 3,
    lessonPath: unitaryCompassMission.lessonPath,
    mission: unitaryCompassMission,
    component: UnitaryCompassMission,
    meta: {
      title: 'Унитарный компас',
      formula: String.raw`\langle x,y\rangle=\sum x_k\overline{y_k},\quad U^*U=I`,
      description:
        'Комплексная фаза, сопряжение и унитарность становятся проверяемой геометрией.',
    },
  },
  {
    id: 'substitution-workshop',
    path: '/algebra/substitutions/workshop',
    title: 'Цех перестановок',
    kind: 'mission',
    status: 'available',
    difficulty: 1,
    lessonPath: substitutionWorkshopMission.lessonPath,
    mission: substitutionWorkshopMission,
    component: SubstitutionWorkshopMission,
    meta: {
      title: 'Цех перестановок',
      formula: String.raw`\operatorname{sgn}(\sigma)=(-1)^{\mathrm{inv}(\sigma)}`,
      description:
        'Перестановка меняется транспозициями: циклы, знак и число ходов становятся игровым состоянием.',
    },
  },
  {
    id: 'graph-dispatcher',
    path: '/combinatorics/graphs/dispatcher',
    title: 'Графовый диспетчер',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: graphDispatcherMission.lessonPath,
    mission: graphDispatcherMission,
    component: GraphDispatcherMission,
    meta: {
      title: 'Графовый диспетчер',
      formula: String.raw`\mathrm{frontier}\rightarrow\mathrm{current}\rightarrow\mathrm{visited}`,
      description:
        'BFS и DFS становятся trace-состояниями: очередь, стек, посещенные вершины и стоимость шагов.',
    },
  },
  {
    id: 'asymptotic-arena',
    path: '/algorithms/asymptotics/arena',
    title: 'Арена асимптотик',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: asymptoticArenaMission.lessonPath,
    mission: asymptoticArenaMission,
    component: AsymptoticArenaMission,
    meta: {
      title: 'Арена асимптотик',
      formula: String.raw`\mathrm{total}=\mathrm{setup}+\mathrm{comparisons}`,
      description:
        'Стратегии сравниваются по модели стоимости: рост, setup, память и число запросов становятся игровыми условиями.',
    },
  },
  {
    id: 'ml-playground',
    path: '/data/ml/playground',
    title: 'ML-полигон',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: mlPlaygroundMission.lessonPath,
    mission: mlPlaygroundMission,
    component: MlPlaygroundMission,
    meta: {
      title: 'ML-полигон',
      formula: String.raw`\mathrm{score}_{test}\neq\mathrm{score}_{train}`,
      description:
        'Пороговая модель проверяется на train/test: метрики, ошибки и leakage становятся игровыми условиями.',
    },
  },
  {
    id: 'feature-factory',
    path: '/data/features/factory',
    title: 'Фабрика признаков',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: featureFactoryMission.lessonPath,
    mission: featureFactoryMission,
    component: FeatureFactoryMission,
    meta: {
      title: 'Фабрика признаков',
      formula: String.raw`\mathrm{raw\ data}\rightarrow\mathrm{features}\rightarrow\mathrm{honest\ score}`,
      description:
        'Пропуски, выбросы, leakage и категории становятся pipeline-шагами, которые меняют устойчивость модели.',
    },
  },
  {
    id: 'bernoulli-lab',
    path: '/probability/bernoulli/lab',
    title: 'Бернулли-лаборатория',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: bernoulliLabMission.lessonPath,
    mission: bernoulliLabMission,
    component: BernoulliLabMission,
    meta: {
      title: 'Бернулли-лаборатория',
      formula: String.raw`\hat{p}=\frac{k}{n}\xrightarrow{n\to\infty}p`,
      description:
        'Частота решек в выборке оценивает вероятность: малое n шумит, большое n стабилизирует оценку.',
    },
  },
  {
    id: 'gradient-slope',
    path: '/calculus/gradient/slope',
    title: 'Градиентный склон',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: gradientSlopeMission.lessonPath,
    mission: gradientSlopeMission,
    component: GradientSlopeMission,
    meta: {
      title: 'Градиентный склон',
      formula: String.raw`x_{k+1}=x_k-\eta\nabla f(x_k)`,
      description:
        'Шаг градиентного спуска балансирует learning rate и кривизну: малый ползёт, большой расходится, узкая ось задаёт предел.',
    },
  },
  {
    id: 'heap-forge',
    path: '/algorithms/heaps/forge',
    title: 'Куча-кузница',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: heapForgeMission.lessonPath,
    mission: heapForgeMission,
    component: HeapForgeMission,
    meta: {
      title: 'Куча-кузница',
      formula: String.raw`a[\lfloor (i-1)/2 \rfloor] \le a[i]`,
      description:
        'Двоичная min-heap как дерево: красные рёбра показывают нарушения parent > child, обмены восстанавливают инвариант.',
    },
  },
  {
    id: 'roots-orbit',
    path: '/algebra/complex-numbers/roots',
    title: 'Орбита корней',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: rootsOrbitMission.lessonPath,
    mission: rootsOrbitMission,
    component: RootsOrbitMission,
    meta: {
      title: 'Орбита корней',
      formula: String.raw`z_k=e^{2\pi i k/n},\quad z^n=1`,
      description:
        'Степени комплексного z обходят окружность: первообразный корень e^{2pi i/n} замыкает правильный n-угольник в единице.',
    },
  },
  {
    id: 'fourier-synth',
    path: '/calculus/fourier/synth',
    title: 'Фурье-синтезатор',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: fourierSynthMission.lessonPath,
    mission: fourierSynthMission,
    component: FourierSynthMission,
    meta: {
      title: 'Фурье-синтезатор',
      formula: String.raw`f(x)\approx\sum_{k=1}^{n} a_k\sin(kx)`,
      description:
        'Сигнал собирается из гармоник: амплитуды задают спектр, а энергия ошибки падает по мере совпадения с целевым сигналом.',
    },
  },
  {
    id: 'monte-carlo',
    path: '/probability/monte-carlo/area',
    title: 'Монте-Карло',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: monteCarloMission.lessonPath,
    mission: monteCarloMission,
    component: MonteCarloMission,
    meta: {
      title: 'Монте-Карло',
      formula: String.raw`P=\frac{S_{\text{обл}}}{S},\quad \hat P=\frac{\#\text{внутри}}{n}`,
      description:
        'Геометрическая вероятность как отношение площадей: доля случайных точек внутри области оценивает её площадь.',
    },
  },
  {
    id: 'bayes-fork',
    path: '/probability/bayes/fork',
    title: 'Байесова развилка',
    kind: 'mission',
    status: 'available',
    difficulty: 3,
    lessonPath: bayesForkMission.lessonPath,
    mission: bayesForkMission,
    component: BayesForkMission,
    meta: {
      title: 'Байесова развилка',
      formula: String.raw`P(D\mid+)=\frac{P(+\mid D)\,P(D)}{P(+\mid D)\,P(D)+P(+\mid\neg D)\,P(\neg D)}`,
      description:
        'Условная вероятность как доля по срезу таблицы: формула Байеса поворачивает условие и учитывает базовую частоту.',
    },
  },
  {
    id: 'expectation-lab',
    path: '/probability/expectation/lab',
    title: 'Среднее и разброс',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: expectationLabMission.lessonPath,
    mission: expectationLabMission,
    component: ExpectationLabMission,
    meta: {
      title: 'Среднее и разброс',
      formula: String.raw`E[X]=\sum_i x_i p_i,\quad \mathrm{Var}[X]=\sum_i p_i\,(x_i-E[X])^2`,
      description:
        'Математическое ожидание как предел выборочного среднего, а дисперсия — как средний квадрат отклонения.',
    },
  },
  {
    id: 'taylor-lab',
    path: '/calculus/taylor/lab',
    title: 'Полином Тейлора',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: taylorLabMission.lessonPath,
    mission: taylorLabMission,
    component: TaylorLabMission,
    meta: {
      title: 'Полином Тейлора',
      formula: String.raw`f(x)\approx\sum_{k=0}^{n}\frac{f^{(k)}(0)}{k!}\,x^k`,
      description:
        'Приближение функции полиномом Тейлора: касательная, кривизна и старшие члены прижимают полином к функции у нуля.',
    },
  },
  {
    id: 'pascal-triangle',
    path: '/combinatorics/pascal/triangle',
    title: 'Треугольник Паскаля',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: pascalTriangleMission.lessonPath,
    mission: pascalTriangleMission,
    component: PascalTriangleMission,
    meta: {
      title: 'Треугольник Паскаля',
      formula: String.raw`\binom{n}{k}=\binom{n-1}{k-1}+\binom{n-1}{k}`,
      description:
        'Биномиальные коэффициенты как рекуррентность: каждая клетка — сумма двух соседок сверху, рёбра равны единице.',
    },
  },
  {
    id: 'gauss-station',
    path: '/algebra/linear-equations/gauss',
    title: 'Гаусс-станция',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: gaussStationMission.lessonPath,
    mission: gaussStationMission,
    component: GaussStationMission,
    meta: {
      title: 'Гаусс-станция',
      formula: String.raw`R_i \mathrel{-}= \frac{a_{ij}}{a_{jj}} R_j`,
      description:
        'Прямой ход метода Гаусса: элементы под диагональю обнуляются опорными строками, система приводится к ступенчатому виду.',
    },
  },
  {
    id: 'dsu-forest',
    path: '/algorithms/dsu/forest',
    title: 'Лес связности',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: dsuForestMission.lessonPath,
    mission: dsuForestMission,
    component: DsuForestMission,
    meta: {
      title: 'Лес связности',
      formula: String.raw`\text{find}(a)=\text{find}(b)\;\Rightarrow\;\text{цикл}`,
      description:
        'Союз непересекающихся множеств: рёбра объединяют компоненты, а ребро внутри одной компоненты замыкает цикл.',
    },
  },
  {
    id: 'dp-station',
    path: '/algorithms/dynamic-programming/edit-distance',
    title: 'DP-станция',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: dpStationMission.lessonPath,
    mission: dpStationMission,
    component: DpStationMission,
    meta: {
      title: 'DP-станция',
      formula: String.raw`D_{ij}=\min(D_{i-1,j},D_{i,j-1},D_{i-1,j-1})+[a_i\ne b_j]`,
      description:
        'Редакционное расстояние как таблица подзадач: каждая клетка считается из left, top и diagonal в правильном порядке.',
    },
  },
  {
    id: 'eigen-chase',
    path: '/algebra/eigenvalues/chase',
    title: 'Собственные векторы',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: eigenChaseMission.lessonPath,
    mission: eigenChaseMission,
    component: EigenChaseMission,
    meta: {
      title: 'Собственные векторы',
      formula: String.raw`A v = \lambda v`,
      description:
        'Собственный вектор - направление, которое матрица только растягивает: A·v параллелен v, а λ задаёт масштаб.',
    },
  },
  {
    id: 'euler-trail',
    path: '/combinatorics/euler/trail',
    title: 'Эйлеров путь',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: eulerTrailMission.lessonPath,
    mission: eulerTrailMission,
    component: EulerTrailMission,
    meta: {
      title: 'Эйлеров путь',
      formula: String.raw`\#\{\deg\,\text{нечёт}\}\in\{0,2\}`,
      description:
        'Маршрут через все рёбра по разу: существует, когда нечётных вершин ноль или ровно две.',
    },
  },
  {
    id: 'bst-quest',
    path: '/algorithms/bst/quest',
    title: 'Дерево поиска',
    kind: 'mission',
    status: 'available',
    difficulty: 2,
    lessonPath: bstQuestMission.lessonPath,
    mission: bstQuestMission,
    component: BstQuestMission,
    meta: {
      title: 'Дерево поиска',
      formula: String.raw`\text{left} < \text{node} < \text{right}`,
      description:
        'Двоичное дерево поиска: меньше узла - влево, больше - вправо, поиск за высоту дерева.',
    },
  },
]
