import type { CurriculumNode } from './curriculumTypes'

export const curriculumGraph: CurriculumNode[] = [
  {
    id: 'substitutions',
    title: 'Подстановки',
    cardLabel: 'Состояния и операции',
    section: 'combinatorics',
    lessonPaths: ['SHAD/algebra/1_Substitutions/lesson.md'],
    qaPaths: ['SHAD/algebra/1_Substitutions/qa.md'],
    prerequisites: [],
    missionIds: ['substitution-workshop'],
    skillIds: ['state-machine', 'cycles', 'parity'],
    unlocks: ['matrices', 'graph-trace'],
    reviewAfterMissionIds: ['matrix-machine'],
    readinessLabel: 'Цех доступен: result/repair-маркеры',
    coverageStatus: 'review-ready',
    takeaway: 'Перестановка меняется транспозициями, а циклы и знак остаются видимыми.',
    status: 'prototype',
  },
  {
    id: 'binomial-coefficients',
    title: 'Биномиальные коэффициенты',
    cardLabel: 'Треугольник Паскаля',
    section: 'combinatorics',
    lessonPaths: ['SHAD/combinatorics/3. Placements/lesson.md'],
    prerequisites: [],
    missionIds: ['pascal-triangle'],
    skillIds: ['binomial-coefficients', 'pascal-recurrence', 'combinations'],
    unlocks: [],
    readinessLabel: 'Треугольник Паскаля доступен',
    coverageStatus: 'review-ready',
    takeaway:
      'Число сочетаний C(n, k) строится рекуррентностью Паскаля; строки симметричны, их суммы равны 2ⁿ.',
    status: 'available',
  },
  {
    id: 'matrices',
    title: 'Матрицы',
    cardLabel: 'Матрица как действие',
    section: 'algebra',
    lessonPaths: ['SHAD/algebra/6_Matrices/lesson.md'],
    prerequisites: ['substitutions'],
    missionIds: ['matrix-machine'],
    skillIds: ['basis-images', 'linear-map-as-columns'],
    unlocks: ['determinants', 'linear-maps-kernel', 'quadratic-forms'],
    reviewAfterMissionIds: ['determinant-forge'],
    readinessLabel: 'Машина доступна: есть challenge-уровни',
    coverageStatus: 'review-ready',
    takeaway: 'Столбцы матрицы - это образы базисных векторов.',
    status: 'prototype',
  },
  {
    id: 'determinants',
    title: 'Определители',
    cardLabel: 'Площадь и ориентация',
    section: 'algebra',
    lessonPaths: ['SHAD/algebra/5_Det/lesson.md'],
    prerequisites: ['matrices'],
    missionIds: ['determinant-forge'],
    skillIds: ['area-scale', 'orientation', 'degeneracy'],
    unlocks: ['linear-maps-kernel', 'quadratic-forms'],
    reviewAfterMissionIds: ['kernel-hunt', 'quadratic-lens'],
    readinessLabel: 'Кузница доступна',
    coverageStatus: 'playable',
    takeaway: 'Определитель хранит масштаб площади, знак и вырожденность.',
    status: 'prototype',
  },
  {
    id: 'linear-maps-kernel',
    title: 'Линейные отображения и ядро',
    cardLabel: 'Схлопнутые направления',
    section: 'algebra',
    lessonPaths: ['SHAD/algebra/8_Linear_maps/lesson.md'],
    prerequisites: ['matrices', 'determinants'],
    missionIds: ['kernel-hunt'],
    skillIds: ['homogeneous-system', 'kernel-basis', 'rank-nullity'],
    unlocks: ['quadratic-forms', 'graph-trace'],
    reviewAfterMissionIds: ['quadratic-lens', 'graph-dispatcher'],
    readinessLabel: 'Residual-диагностика готовится',
    coverageStatus: 'diagnosed',
    takeaway: 'Ядро - подпространство решений Ax = 0.',
    status: 'available',
  },
  {
    id: 'quadratic-forms',
    title: 'Квадратичные формы',
    cardLabel: 'Энергия и главные оси',
    section: 'algebra',
    lessonPaths: ['SHAD/algebra/10_Bilinear_quadratic_forms/lesson.md'],
    qaPaths: ['SHAD/algebra/10_Bilinear_quadratic_forms/qa.md'],
    prerequisites: ['matrices', 'determinants', 'linear-maps-kernel'],
    missionIds: ['quadratic-lens'],
    skillIds: ['quadratic-form', 'signature', 'principal-axes'],
    unlocks: ['euclidean-geometry', 'graph-trace'],
    reviewAfterMissionIds: ['determinant-forge', 'kernel-hunt'],
    readinessLabel: 'Линза доступна: result/repair-маркеры',
    coverageStatus: 'review-ready',
    takeaway:
      'Симметрическая форма измеряет направления через главные оси, determinant и сигнатуру.',
    status: 'prototype',
  },
  {
    id: 'euclidean-geometry',
    title: 'Евклидовы пространства',
    cardLabel: 'Проекция и ортогональность',
    section: 'algebra',
    lessonPaths: ['SHAD/algebra/11_Euclidean_spaces/lesson.md'],
    prerequisites: ['quadratic-forms'],
    missionIds: ['orthogonal-workshop'],
    skillIds: ['orthogonal-projection', 'gram-schmidt', 'orthogonal-operator'],
    unlocks: ['complex-geometry'],
    reviewAfterMissionIds: ['quadratic-lens', 'svd-lens'],
    readinessLabel: 'Мастерская доступна: field-маркеры ошибок',
    coverageStatus: 'review-ready',
    takeaway:
      'Ортогональная проекция оставляет перпендикулярный остаток, а ортонормированный базис сохраняет удобную геометрию.',
    status: 'prototype',
  },
  {
    id: 'complex-geometry',
    title: 'Комплексные пространства',
    cardLabel: 'Фаза и сопряжение',
    section: 'algebra',
    lessonPaths: ['SHAD/algebra/13_Complex_spaces/lesson.md'],
    prerequisites: ['euclidean-geometry'],
    missionIds: ['unitary-compass'],
    skillIds: ['hermitian-inner-product', 'unitary-operator', 'adjoint-matrix'],
    unlocks: ['svd-pca'],
    reviewAfterMissionIds: ['orthogonal-workshop', 'svd-lens'],
    readinessLabel: 'Компас доступен: маркер ошибочного объекта',
    coverageStatus: 'review-ready',
    takeaway:
      'Комплексная геометрия сохраняет длину через сопряжение, Hermitian product и унитарные операторы.',
    status: 'prototype',
  },
  {
    id: 'svd-pca',
    title: 'SVD и PCA',
    cardLabel: 'Круг, эллипс и данные',
    section: 'algebra',
    lessonPaths: ['SHAD/algebra/13_Complex_spaces/lesson.md'],
    prerequisites: ['complex-geometry'],
    missionIds: ['svd-lens', 'pca-compression-lab'],
    skillIds: ['singular-values', 'principal-components', 'low-rank'],
    unlocks: ['ml-playground'],
    reviewAfterMissionIds: ['quadratic-lens', 'unitary-compass', 'feature-factory'],
    readinessLabel: 'SVD/PCA доступны: маркеры + hotspot',
    coverageStatus: 'review-ready',
    takeaway:
      'SVD раскладывает любую матрицу на входные оси, неотрицательные растяжения и выходные оси.',
    status: 'prototype',
  },
  {
    id: 'graph-trace',
    title: 'Графовые обходы',
    cardLabel: 'Trace алгоритма',
    section: 'algorithms',
    lessonPaths: ['SHAD/combinatorics/4. Graphs/lesson.md'],
    qaPaths: ['SHAD/combinatorics/4. Graphs/qa.md'],
    prerequisites: ['substitutions'],
    missionIds: ['graph-dispatcher'],
    plannedMissionIds: ['graph-bridges', 'shortest-paths'],
    skillIds: ['frontier', 'visited', 'trace-invariant'],
    unlocks: ['asymptotics'],
    reviewAfterMissionIds: ['substitution-workshop'],
    readinessLabel: 'Trace доступен',
    coverageStatus: 'playable',
    takeaway:
      'Очередь, стек и посещенные вершины превращают обход в проверяемое состояние.',
    status: 'prototype',
  },
  {
    id: 'asymptotics',
    title: 'Асимптотика',
    cardLabel: 'Стратегия и стоимость',
    section: 'algorithms',
    lessonPaths: ['SHAD/mathematical_analysis/4_asymptotics/lesson.md'],
    prerequisites: ['graph-trace'],
    missionIds: ['asymptotic-arena'],
    plannedMissionIds: ['dp-station', 'ml-playground'],
    skillIds: ['growth-model', 'cost-comparison', 'strategy-choice'],
    unlocks: ['ml-playground'],
    reviewAfterMissionIds: ['graph-dispatcher'],
    readinessLabel: 'Арена доступна: result/repair-маркеры',
    coverageStatus: 'review-ready',
    takeaway: 'Стратегию выбирают по setup, comparisons, памяти и росту на n.',
    status: 'prototype',
  },
  {
    id: 'ml-playground',
    title: 'ML-полигон',
    cardLabel: 'Train/test и метрики',
    section: 'data-analysis',
    lessonPaths: ['SHAD/Programma_dlya_postupayushhih_v_Shkolu_analiza_dannyh_3_749884e44e.md'],
    prerequisites: ['asymptotics'],
    missionIds: ['ml-playground'],
    plannedMissionIds: ['feature-factory', 'decision-tree-split'],
    skillIds: ['train-test-split', 'thresholding', 'metric-tradeoff'],
    unlocks: ['feature-factory'],
    reviewAfterMissionIds: ['asymptotic-arena', 'pca-compression-lab'],
    readinessLabel: 'Полигон доступен: result/repair-маркеры',
    coverageStatus: 'review-ready',
    takeaway: 'Модель выбирают по честному test-контролю, а не по красивой train-метрике.',
    status: 'prototype',
  },
  {
    id: 'feature-factory',
    title: 'Фабрика признаков',
    cardLabel: 'Pipeline данных',
    section: 'data-analysis',
    lessonPaths: ['SHAD/Programma_dlya_postupayushhih_v_Shkolu_analiza_dannyh_3_749884e44e.md'],
    prerequisites: ['ml-playground'],
    missionIds: ['feature-factory'],
    plannedMissionIds: ['decision-tree-split'],
    skillIds: ['missing-values', 'feature-selection', 'leakage-control'],
    unlocks: [],
    reviewAfterMissionIds: ['ml-playground'],
    readinessLabel: 'Feature-pipeline доступен',
    coverageStatus: 'playable',
    takeaway:
      'Хороший признак появляется из явного pipeline: impute, outlier repair, leakage check и encoding.',
    status: 'prototype',
  },
  {
    id: 'probability-basics',
    title: 'Вероятность',
    cardLabel: 'Частота и вероятность',
    section: 'probability',
    lessonPaths: ['SHAD/probability_theory/1_Probability_basics/lesson.md'],
    qaPaths: ['SHAD/probability_theory/1_Probability_basics/qa.md'],
    prerequisites: [],
    missionIds: ['bernoulli-lab'],
    skillIds: ['frequency-estimates-probability', 'sample-size', 'law-of-large-numbers'],
    unlocks: [],
    readinessLabel: 'Бернулли-лаборатория доступна',
    coverageStatus: 'review-ready',
    takeaway:
      'Частота в большой выборке оценивает вероятность, а шум падает как 1/sqrt(n).',
    status: 'available',
  },
  {
    id: 'multivariable-calculus',
    title: 'Функции многих переменных',
    cardLabel: 'Градиент и спуск',
    section: 'calculus',
    lessonPaths: ['SHAD/mathematical_analysis/7_functions_of_many_variables/lesson.md'],
    prerequisites: [],
    missionIds: ['gradient-slope'],
    skillIds: ['gradient-direction', 'step-size', 'ill-conditioning'],
    unlocks: [],
    readinessLabel: 'Градиентный склон доступен',
    coverageStatus: 'review-ready',
    takeaway:
      'Градиентный спуск балансирует шаг и кривизну: малый ползёт, большой расходится.',
    status: 'available',
  },
  {
    id: 'heaps',
    title: 'Кучи',
    cardLabel: 'Инвариант кучи',
    section: 'algorithms',
    lessonPaths: ['SHAD/Programma_dlya_postupayushhih_v_Shkolu_analiza_dannyh_3_749884e44e.md'],
    prerequisites: ['graph-trace'],
    missionIds: ['heap-forge'],
    skillIds: ['heap-invariant', 'sift-up', 'sift-down'],
    unlocks: [],
    readinessLabel: 'Куча-кузница доступна',
    coverageStatus: 'review-ready',
    takeaway:
      'Min-heap держит инвариант parent <= children; обмены по нарушенным рёбрам восстанавливают его.',
    status: 'available',
  },
  {
    id: 'complex-numbers',
    title: 'Комплексные числа',
    cardLabel: 'Корни из единицы',
    section: 'algebra',
    lessonPaths: ['SHAD/algebra/2_Complex numbers/lesson.md'],
    qaPaths: ['SHAD/algebra/2_Complex numbers/qa.md'],
    prerequisites: [],
    missionIds: ['roots-orbit'],
    skillIds: ['complex-powers', 'roots-of-unity', 'primitive-root'],
    unlocks: ['complex-geometry'],
    readinessLabel: 'Орбита корней доступна',
    coverageStatus: 'review-ready',
    takeaway:
      'Степени первообразного корня e^(2pi i/n) обходят правильный n-угольник и возвращаются в 1.',
    status: 'available',
  },
  {
    id: 'fourier-series',
    title: 'Ряды Фурье',
    cardLabel: 'Сигнал из гармоник',
    section: 'calculus',
    lessonPaths: ['SHAD/mathematical_analysis/11_series_fourier/lesson.md'],
    prerequisites: ['multivariable-calculus'],
    missionIds: ['fourier-synth'],
    skillIds: ['harmonics', 'spectrum', 'l2-approximation'],
    unlocks: [],
    readinessLabel: 'Фурье-синтезатор доступен',
    coverageStatus: 'review-ready',
    takeaway:
      'Сигнал раскладывается в сумму гармоник; ошибка приближения — это энергия несовпадения спектров.',
    status: 'available',
  },
  {
    id: 'taylor-series',
    title: 'Полином Тейлора',
    cardLabel: 'Касательная и кривизна',
    section: 'calculus',
    lessonPaths: ['SHAD/mathematical_analysis/6_derivative_applications/lesson.md'],
    qaPaths: ['SHAD/mathematical_analysis/6_derivative_applications/qa.md'],
    prerequisites: [],
    missionIds: ['taylor-lab'],
    skillIds: ['linear-approximation', 'taylor-coefficients', 'higher-derivatives'],
    unlocks: [],
    readinessLabel: 'Полином Тейлора доступен',
    coverageStatus: 'review-ready',
    takeaway:
      'Ряд Тейлора приближает функцию полиномом: коэффициент при x^k — это k-я производная в нуле, делённая на k!.',
    status: 'available',
  },
  {
    id: 'geometric-probability',
    title: 'Геометрическая вероятность',
    cardLabel: 'Площадь как вероятность',
    section: 'probability',
    lessonPaths: ['SHAD/probability_theory/1_Probability_basics/lesson.md'],
    qaPaths: ['SHAD/probability_theory/1_Probability_basics/qa.md'],
    prerequisites: ['probability-basics'],
    missionIds: ['monte-carlo'],
    skillIds: ['monte-carlo', 'area-as-probability', 'sample-variance'],
    unlocks: [],
    readinessLabel: 'Монте-Карло доступен',
    coverageStatus: 'review-ready',
    takeaway:
      'Геометрическая вероятность = отношение площадей; Монте-Карло оценивает её долей попаданий.',
    status: 'available',
  },
  {
    id: 'conditional-probability',
    title: 'Условная вероятность и Байес',
    cardLabel: 'Условие и апостериор',
    section: 'probability',
    lessonPaths: ['SHAD/probability_theory/1_Probability_basics/lesson.md'],
    qaPaths: ['SHAD/probability_theory/1_Probability_basics/qa.md'],
    prerequisites: ['probability-basics'],
    missionIds: ['bayes-fork'],
    skillIds: ['conditional-probability', 'bayes-rule', 'base-rate'],
    unlocks: [],
    readinessLabel: 'Байесова развилка доступна',
    coverageStatus: 'review-ready',
    takeaway:
      'Условная вероятность — доля по срезу таблицы; формула Байеса поворачивает условие и учитывает базовую частоту.',
    status: 'available',
  },
  {
    id: 'expectation-variance',
    title: 'Ожидание и дисперсия',
    cardLabel: 'Среднее и разброс',
    section: 'probability',
    lessonPaths: ['SHAD/probability_theory/1_Probability_basics/lesson.md'],
    qaPaths: ['SHAD/probability_theory/1_Probability_basics/qa.md'],
    prerequisites: ['probability-basics'],
    missionIds: ['expectation-lab'],
    skillIds: ['expectation', 'variance', 'sample-mean-estimator'],
    unlocks: [],
    readinessLabel: 'Среднее и разброс доступны',
    coverageStatus: 'review-ready',
    takeaway:
      'Ожидание — предел выборочного среднего, дисперсия — средний квадрат отклонения (не путать со стандартным отклонением).',
    status: 'available',
  },
  {
    id: 'linear-equations',
    title: 'Линейные уравнения',
    cardLabel: 'Метод Гаусса',
    section: 'algebra',
    lessonPaths: ['SHAD/algebra/3_Linear_equations/lesson.md'],
    qaPaths: ['SHAD/algebra/3_Linear_equations/qa.md'],
    prerequisites: [],
    missionIds: ['gauss-station'],
    skillIds: ['row-reduction', 'pivot-swap', 'back-substitution'],
    unlocks: ['matrices'],
    readinessLabel: 'Гаусс-станция доступна',
    coverageStatus: 'review-ready',
    takeaway:
      'Прямой ход Гаусса обнуляет элементы под диагональю; ступенчатый вид решается обратным ходом.',
    status: 'available',
  },
  {
    id: 'disjoint-sets',
    title: 'Непересекающиеся множества',
    cardLabel: 'Союзы и компоненты',
    section: 'algorithms',
    lessonPaths: ['SHAD/Programma_dlya_postupayushhih_v_Shkolu_analiza_dannyh_3_749884e44e.md'],
    prerequisites: ['graph-trace'],
    missionIds: ['dsu-forest'],
    skillIds: ['union-find', 'connected-components', 'cycle-detection'],
    unlocks: [],
    readinessLabel: 'Лес связности доступен',
    coverageStatus: 'review-ready',
    takeaway:
      'DSU объединяет множества и отвечает на связность; ребро внутри компоненты - цикл.',
    status: 'available',
  },
  {
    id: 'dynamic-programming',
    title: 'Динамическое программирование',
    cardLabel: 'Таблица подзадач',
    section: 'algorithms',
    lessonPaths: ['SHAD/Programma_dlya_postupayushhih_v_Shkolu_analiza_dannyh_3_749884e44e.md'],
    prerequisites: ['graph-trace'],
    missionIds: ['dp-station'],
    skillIds: ['subproblem-order', 'recurrence', 'edit-distance'],
    unlocks: [],
    readinessLabel: 'DP-станция доступна',
    coverageStatus: 'review-ready',
    takeaway:
      'Динамика заполняет таблицу подзадач в правильном порядке: клетка зависит от уже посчитанных соседок.',
    status: 'available',
  },
  {
    id: 'eigenvalues',
    title: 'Собственные значения',
    cardLabel: 'Сохранённые направления',
    section: 'algebra',
    lessonPaths: ['SHAD/algebra/12_Eigenvectors_eigenvalues/lesson.md'],
    qaPaths: ['SHAD/algebra/12_Eigenvectors_eigenvalues/qa.md'],
    prerequisites: ['matrices'],
    missionIds: ['eigen-chase'],
    skillIds: ['eigenvector', 'eigenvalue', 'invariant-direction'],
    unlocks: [],
    readinessLabel: 'Поиск собственных векторов доступен',
    coverageStatus: 'review-ready',
    takeaway:
      'Собственный вектор - направление, которое матрица только растягивает в λ раз, не поворачивая.',
    status: 'available',
  },
  {
    id: 'euler-trails',
    title: 'Эйлеровы пути',
    cardLabel: 'Не отрывая руки',
    section: 'combinatorics',
    lessonPaths: ['SHAD/combinatorics/4. Graphs/lesson.md'],
    qaPaths: ['SHAD/combinatorics/4. Graphs/qa.md'],
    prerequisites: ['graph-trace'],
    missionIds: ['euler-trail'],
    skillIds: ['degree-parity', 'euler-path', 'one-stroke'],
    unlocks: [],
    readinessLabel: 'Эйлеров путь доступен',
    coverageStatus: 'review-ready',
    takeaway:
      'Эйлеров путь существует, когда нечётных вершин ноль (цикл) или ровно две (путь между ними).',
    status: 'available',
  },
  {
    id: 'binary-search-tree',
    title: 'Деревья поиска',
    cardLabel: 'Поиск по сравнениям',
    section: 'algorithms',
    lessonPaths: ['SHAD/Programma_dlya_postupayushhih_v_Shkolu_analiza_dannyh_3_749884e44e.md'],
    prerequisites: ['graph-trace'],
    missionIds: ['bst-quest'],
    skillIds: ['bst-invariant', 'binary-search', 'tree-height'],
    unlocks: [],
    readinessLabel: 'Дерево поиска доступно',
    coverageStatus: 'review-ready',
    takeaway:
      'В дереве поиска левое поддерево меньше узла, правое больше; поиск идёт по сравнениям за высоту.',
    status: 'available',
  },
]

export function validateCurriculumGraph(
  nodes: CurriculumNode[],
  knownMissionIds: Set<string>,
): string[] {
  const errors: string[] = []
  const nodeIds = new Set(nodes.map((node) => node.id))

  for (const node of nodes) {
    for (const prerequisite of node.prerequisites) {
      if (!nodeIds.has(prerequisite)) {
        errors.push(`${node.id}: unknown prerequisite ${prerequisite}`)
      }
    }
    for (const missionId of node.missionIds) {
      if (!knownMissionIds.has(missionId)) {
        errors.push(`${node.id}: unknown mission ${missionId}`)
      }
    }
    for (const unlock of node.unlocks) {
      if (!nodeIds.has(unlock)) {
        errors.push(`${node.id}: unknown unlock ${unlock}`)
      }
    }
    for (const reviewMissionId of node.reviewAfterMissionIds ?? []) {
      if (!knownMissionIds.has(reviewMissionId)) {
        errors.push(`${node.id}: unknown review mission ${reviewMissionId}`)
      }
    }
    if (node.lessonPaths.length === 0) {
      errors.push(`${node.id}: lessonPaths must not be empty`)
    }
    if (node.skillIds.length === 0) {
      errors.push(`${node.id}: skillIds must not be empty`)
    }
  }

  return errors
}
